/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AuthRegisterIndexImport } from './routes/auth/register/index'
import { Route as AuthLoginIndexImport } from './routes/auth/login/index'
import { Route as AuthRegisterOrangTuaIndexImport } from './routes/auth/register/orang-tua/index'
import { Route as AuthRegisterMahasiswaIndexImport } from './routes/auth/register/mahasiswa/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthRegisterIndexRoute = AuthRegisterIndexImport.update({
  id: '/auth/register/',
  path: '/auth/register/',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginIndexRoute = AuthLoginIndexImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRoute,
} as any)

const AuthRegisterOrangTuaIndexRoute = AuthRegisterOrangTuaIndexImport.update({
  id: '/auth/register/orang-tua/',
  path: '/auth/register/orang-tua/',
  getParentRoute: () => rootRoute,
} as any)

const AuthRegisterMahasiswaIndexRoute = AuthRegisterMahasiswaIndexImport.update(
  {
    id: '/auth/register/mahasiswa/',
    path: '/auth/register/mahasiswa/',
    getParentRoute: () => rootRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/register/': {
      id: '/auth/register/'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/register/mahasiswa/': {
      id: '/auth/register/mahasiswa/'
      path: '/auth/register/mahasiswa'
      fullPath: '/auth/register/mahasiswa'
      preLoaderRoute: typeof AuthRegisterMahasiswaIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/register/orang-tua/': {
      id: '/auth/register/orang-tua/'
      path: '/auth/register/orang-tua'
      fullPath: '/auth/register/orang-tua'
      preLoaderRoute: typeof AuthRegisterOrangTuaIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/auth/register/mahasiswa': typeof AuthRegisterMahasiswaIndexRoute
  '/auth/register/orang-tua': typeof AuthRegisterOrangTuaIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/auth/register/mahasiswa': typeof AuthRegisterMahasiswaIndexRoute
  '/auth/register/orang-tua': typeof AuthRegisterOrangTuaIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/auth/register/mahasiswa/': typeof AuthRegisterMahasiswaIndexRoute
  '/auth/register/orang-tua/': typeof AuthRegisterOrangTuaIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/auth/register/mahasiswa'
    | '/auth/register/orang-tua'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/auth/register/mahasiswa'
    | '/auth/register/orang-tua'
  id:
    | '__root__'
    | '/'
    | '/auth/login/'
    | '/auth/register/'
    | '/auth/register/mahasiswa/'
    | '/auth/register/orang-tua/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
  AuthRegisterMahasiswaIndexRoute: typeof AuthRegisterMahasiswaIndexRoute
  AuthRegisterOrangTuaIndexRoute: typeof AuthRegisterOrangTuaIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
  AuthRegisterMahasiswaIndexRoute: AuthRegisterMahasiswaIndexRoute,
  AuthRegisterOrangTuaIndexRoute: AuthRegisterOrangTuaIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth/login/",
        "/auth/register/",
        "/auth/register/mahasiswa/",
        "/auth/register/orang-tua/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth/login/": {
      "filePath": "auth/login/index.tsx"
    },
    "/auth/register/": {
      "filePath": "auth/register/index.tsx"
    },
    "/auth/register/mahasiswa/": {
      "filePath": "auth/register/mahasiswa/index.tsx"
    },
    "/auth/register/orang-tua/": {
      "filePath": "auth/register/orang-tua/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
