/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppImport } from './routes/_app'
import { Route as IndexImport } from './routes/index'
import { Route as AuthVerificationIndexImport } from './routes/auth/verification/index'
import { Route as AuthRegisterIndexImport } from './routes/auth/register/index'
import { Route as AuthLoginIndexImport } from './routes/auth/login/index'
import { Route as AppProtectedExampleIndexImport } from './routes/_app/protected-example/index'
import { Route as AuthRegisterOrangTuaIndexImport } from './routes/auth/register/orang-tua/index'
import { Route as AuthRegisterMahasiswaIndexImport } from './routes/auth/register/mahasiswa/index'

// Create/Update Routes

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthVerificationIndexRoute = AuthVerificationIndexImport.update({
  id: '/auth/verification/',
  path: '/auth/verification/',
  getParentRoute: () => rootRoute,
} as any)

const AuthRegisterIndexRoute = AuthRegisterIndexImport.update({
  id: '/auth/register/',
  path: '/auth/register/',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginIndexRoute = AuthLoginIndexImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRoute,
} as any)

const AppProtectedExampleIndexRoute = AppProtectedExampleIndexImport.update({
  id: '/protected-example/',
  path: '/protected-example/',
  getParentRoute: () => AppRoute,
} as any)

const AuthRegisterOrangTuaIndexRoute = AuthRegisterOrangTuaIndexImport.update({
  id: '/auth/register/orang-tua/',
  path: '/auth/register/orang-tua/',
  getParentRoute: () => rootRoute,
} as any)

const AuthRegisterMahasiswaIndexRoute = AuthRegisterMahasiswaIndexImport.update(
  {
    id: '/auth/register/mahasiswa/',
    path: '/auth/register/mahasiswa/',
    getParentRoute: () => rootRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_app/protected-example/': {
      id: '/_app/protected-example/'
      path: '/protected-example'
      fullPath: '/protected-example'
      preLoaderRoute: typeof AppProtectedExampleIndexImport
      parentRoute: typeof AppImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/register/': {
      id: '/auth/register/'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/verification/': {
      id: '/auth/verification/'
      path: '/auth/verification'
      fullPath: '/auth/verification'
      preLoaderRoute: typeof AuthVerificationIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/register/mahasiswa/': {
      id: '/auth/register/mahasiswa/'
      path: '/auth/register/mahasiswa'
      fullPath: '/auth/register/mahasiswa'
      preLoaderRoute: typeof AuthRegisterMahasiswaIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/register/orang-tua/': {
      id: '/auth/register/orang-tua/'
      path: '/auth/register/orang-tua'
      fullPath: '/auth/register/orang-tua'
      preLoaderRoute: typeof AuthRegisterOrangTuaIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface AppRouteChildren {
  AppProtectedExampleIndexRoute: typeof AppProtectedExampleIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProtectedExampleIndexRoute: AppProtectedExampleIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AppRouteWithChildren
  '/protected-example': typeof AppProtectedExampleIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/auth/verification': typeof AuthVerificationIndexRoute
  '/auth/register/mahasiswa': typeof AuthRegisterMahasiswaIndexRoute
  '/auth/register/orang-tua': typeof AuthRegisterOrangTuaIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AppRouteWithChildren
  '/protected-example': typeof AppProtectedExampleIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/auth/verification': typeof AuthVerificationIndexRoute
  '/auth/register/mahasiswa': typeof AuthRegisterMahasiswaIndexRoute
  '/auth/register/orang-tua': typeof AuthRegisterOrangTuaIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/protected-example/': typeof AppProtectedExampleIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/auth/verification/': typeof AuthVerificationIndexRoute
  '/auth/register/mahasiswa/': typeof AuthRegisterMahasiswaIndexRoute
  '/auth/register/orang-tua/': typeof AuthRegisterOrangTuaIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/protected-example'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verification'
    | '/auth/register/mahasiswa'
    | '/auth/register/orang-tua'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/protected-example'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verification'
    | '/auth/register/mahasiswa'
    | '/auth/register/orang-tua'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/protected-example/'
    | '/auth/login/'
    | '/auth/register/'
    | '/auth/verification/'
    | '/auth/register/mahasiswa/'
    | '/auth/register/orang-tua/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
  AuthVerificationIndexRoute: typeof AuthVerificationIndexRoute
  AuthRegisterMahasiswaIndexRoute: typeof AuthRegisterMahasiswaIndexRoute
  AuthRegisterOrangTuaIndexRoute: typeof AuthRegisterOrangTuaIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
  AuthVerificationIndexRoute: AuthVerificationIndexRoute,
  AuthRegisterMahasiswaIndexRoute: AuthRegisterMahasiswaIndexRoute,
  AuthRegisterOrangTuaIndexRoute: AuthRegisterOrangTuaIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_app",
        "/auth/login/",
        "/auth/register/",
        "/auth/verification/",
        "/auth/register/mahasiswa/",
        "/auth/register/orang-tua/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/protected-example/"
      ]
    },
    "/_app/protected-example/": {
      "filePath": "_app/protected-example/index.tsx",
      "parent": "/_app"
    },
    "/auth/login/": {
      "filePath": "auth/login/index.tsx"
    },
    "/auth/register/": {
      "filePath": "auth/register/index.tsx"
    },
    "/auth/verification/": {
      "filePath": "auth/verification/index.tsx"
    },
    "/auth/register/mahasiswa/": {
      "filePath": "auth/register/mahasiswa/index.tsx"
    },
    "/auth/register/orang-tua/": {
      "filePath": "auth/register/orang-tua/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
