/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppImport } from './routes/_app'
import { Route as IndexImport } from './routes/index'
import { Route as AuthVerificationIndexImport } from './routes/auth/verification/index'
import { Route as AuthRegisterIndexImport } from './routes/auth/register/index'
import { Route as AuthLoginIndexImport } from './routes/auth/login/index'
import { Route as AppProtectedExampleIndexImport } from './routes/_app/protected-example/index'
import { Route as AppProfileIndexImport } from './routes/_app/profile/index'
import { Route as AuthRegisterOrangTuaIndexImport } from './routes/auth/register/orang-tua/index'
import { Route as AuthRegisterMahasiswaIndexImport } from './routes/auth/register/mahasiswa/index'
import { Route as AppDaftarMahasiswaIndexImport } from './routes/_app/daftar/mahasiswa/index'
import { Route as AppDaftarMahasiswaSayaIndexImport } from './routes/_app/daftar/mahasiswa-saya/index'
import { Route as IntegrationsAzureKeyVaultOauth2CallbackIndexImport } from './routes/integrations/azure-key-vault/oauth2/callback/index'

// Create/Update Routes

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthVerificationIndexRoute = AuthVerificationIndexImport.update({
  id: '/auth/verification/',
  path: '/auth/verification/',
  getParentRoute: () => rootRoute,
} as any)

const AuthRegisterIndexRoute = AuthRegisterIndexImport.update({
  id: '/auth/register/',
  path: '/auth/register/',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginIndexRoute = AuthLoginIndexImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRoute,
} as any)

const AppProtectedExampleIndexRoute = AppProtectedExampleIndexImport.update({
  id: '/protected-example/',
  path: '/protected-example/',
  getParentRoute: () => AppRoute,
} as any)

const AppProfileIndexRoute = AppProfileIndexImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppRoute,
} as any)

const AuthRegisterOrangTuaIndexRoute = AuthRegisterOrangTuaIndexImport.update({
  id: '/auth/register/orang-tua/',
  path: '/auth/register/orang-tua/',
  getParentRoute: () => rootRoute,
} as any)

const AuthRegisterMahasiswaIndexRoute = AuthRegisterMahasiswaIndexImport.update(
  {
    id: '/auth/register/mahasiswa/',
    path: '/auth/register/mahasiswa/',
    getParentRoute: () => rootRoute,
  } as any,
)

const AppDaftarMahasiswaIndexRoute = AppDaftarMahasiswaIndexImport.update({
  id: '/daftar/mahasiswa/',
  path: '/daftar/mahasiswa/',
  getParentRoute: () => AppRoute,
} as any)

const AppDaftarMahasiswaSayaIndexRoute =
  AppDaftarMahasiswaSayaIndexImport.update({
    id: '/daftar/mahasiswa-saya/',
    path: '/daftar/mahasiswa-saya/',
    getParentRoute: () => AppRoute,
  } as any)

const IntegrationsAzureKeyVaultOauth2CallbackIndexRoute =
  IntegrationsAzureKeyVaultOauth2CallbackIndexImport.update({
    id: '/integrations/azure-key-vault/oauth2/callback/',
    path: '/integrations/azure-key-vault/oauth2/callback/',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_app/profile/': {
      id: '/_app/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/protected-example/': {
      id: '/_app/protected-example/'
      path: '/protected-example'
      fullPath: '/protected-example'
      preLoaderRoute: typeof AppProtectedExampleIndexImport
      parentRoute: typeof AppImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/register/': {
      id: '/auth/register/'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/verification/': {
      id: '/auth/verification/'
      path: '/auth/verification'
      fullPath: '/auth/verification'
      preLoaderRoute: typeof AuthVerificationIndexImport
      parentRoute: typeof rootRoute
    }
    '/_app/daftar/mahasiswa-saya/': {
      id: '/_app/daftar/mahasiswa-saya/'
      path: '/daftar/mahasiswa-saya'
      fullPath: '/daftar/mahasiswa-saya'
      preLoaderRoute: typeof AppDaftarMahasiswaSayaIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/daftar/mahasiswa/': {
      id: '/_app/daftar/mahasiswa/'
      path: '/daftar/mahasiswa'
      fullPath: '/daftar/mahasiswa'
      preLoaderRoute: typeof AppDaftarMahasiswaIndexImport
      parentRoute: typeof AppImport
    }
    '/auth/register/mahasiswa/': {
      id: '/auth/register/mahasiswa/'
      path: '/auth/register/mahasiswa'
      fullPath: '/auth/register/mahasiswa'
      preLoaderRoute: typeof AuthRegisterMahasiswaIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/register/orang-tua/': {
      id: '/auth/register/orang-tua/'
      path: '/auth/register/orang-tua'
      fullPath: '/auth/register/orang-tua'
      preLoaderRoute: typeof AuthRegisterOrangTuaIndexImport
      parentRoute: typeof rootRoute
    }
    '/integrations/azure-key-vault/oauth2/callback/': {
      id: '/integrations/azure-key-vault/oauth2/callback/'
      path: '/integrations/azure-key-vault/oauth2/callback'
      fullPath: '/integrations/azure-key-vault/oauth2/callback'
      preLoaderRoute: typeof IntegrationsAzureKeyVaultOauth2CallbackIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface AppRouteChildren {
  AppProfileIndexRoute: typeof AppProfileIndexRoute
  AppProtectedExampleIndexRoute: typeof AppProtectedExampleIndexRoute
  AppDaftarMahasiswaSayaIndexRoute: typeof AppDaftarMahasiswaSayaIndexRoute
  AppDaftarMahasiswaIndexRoute: typeof AppDaftarMahasiswaIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProfileIndexRoute: AppProfileIndexRoute,
  AppProtectedExampleIndexRoute: AppProtectedExampleIndexRoute,
  AppDaftarMahasiswaSayaIndexRoute: AppDaftarMahasiswaSayaIndexRoute,
  AppDaftarMahasiswaIndexRoute: AppDaftarMahasiswaIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AppRouteWithChildren
  '/profile': typeof AppProfileIndexRoute
  '/protected-example': typeof AppProtectedExampleIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/auth/verification': typeof AuthVerificationIndexRoute
  '/daftar/mahasiswa-saya': typeof AppDaftarMahasiswaSayaIndexRoute
  '/daftar/mahasiswa': typeof AppDaftarMahasiswaIndexRoute
  '/auth/register/mahasiswa': typeof AuthRegisterMahasiswaIndexRoute
  '/auth/register/orang-tua': typeof AuthRegisterOrangTuaIndexRoute
  '/integrations/azure-key-vault/oauth2/callback': typeof IntegrationsAzureKeyVaultOauth2CallbackIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AppRouteWithChildren
  '/profile': typeof AppProfileIndexRoute
  '/protected-example': typeof AppProtectedExampleIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/auth/verification': typeof AuthVerificationIndexRoute
  '/daftar/mahasiswa-saya': typeof AppDaftarMahasiswaSayaIndexRoute
  '/daftar/mahasiswa': typeof AppDaftarMahasiswaIndexRoute
  '/auth/register/mahasiswa': typeof AuthRegisterMahasiswaIndexRoute
  '/auth/register/orang-tua': typeof AuthRegisterOrangTuaIndexRoute
  '/integrations/azure-key-vault/oauth2/callback': typeof IntegrationsAzureKeyVaultOauth2CallbackIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/profile/': typeof AppProfileIndexRoute
  '/_app/protected-example/': typeof AppProtectedExampleIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/auth/verification/': typeof AuthVerificationIndexRoute
  '/_app/daftar/mahasiswa-saya/': typeof AppDaftarMahasiswaSayaIndexRoute
  '/_app/daftar/mahasiswa/': typeof AppDaftarMahasiswaIndexRoute
  '/auth/register/mahasiswa/': typeof AuthRegisterMahasiswaIndexRoute
  '/auth/register/orang-tua/': typeof AuthRegisterOrangTuaIndexRoute
  '/integrations/azure-key-vault/oauth2/callback/': typeof IntegrationsAzureKeyVaultOauth2CallbackIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/profile'
    | '/protected-example'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verification'
    | '/daftar/mahasiswa-saya'
    | '/daftar/mahasiswa'
    | '/auth/register/mahasiswa'
    | '/auth/register/orang-tua'
    | '/integrations/azure-key-vault/oauth2/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/profile'
    | '/protected-example'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verification'
    | '/daftar/mahasiswa-saya'
    | '/daftar/mahasiswa'
    | '/auth/register/mahasiswa'
    | '/auth/register/orang-tua'
    | '/integrations/azure-key-vault/oauth2/callback'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/profile/'
    | '/_app/protected-example/'
    | '/auth/login/'
    | '/auth/register/'
    | '/auth/verification/'
    | '/_app/daftar/mahasiswa-saya/'
    | '/_app/daftar/mahasiswa/'
    | '/auth/register/mahasiswa/'
    | '/auth/register/orang-tua/'
    | '/integrations/azure-key-vault/oauth2/callback/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
  AuthVerificationIndexRoute: typeof AuthVerificationIndexRoute
  AuthRegisterMahasiswaIndexRoute: typeof AuthRegisterMahasiswaIndexRoute
  AuthRegisterOrangTuaIndexRoute: typeof AuthRegisterOrangTuaIndexRoute
  IntegrationsAzureKeyVaultOauth2CallbackIndexRoute: typeof IntegrationsAzureKeyVaultOauth2CallbackIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
  AuthVerificationIndexRoute: AuthVerificationIndexRoute,
  AuthRegisterMahasiswaIndexRoute: AuthRegisterMahasiswaIndexRoute,
  AuthRegisterOrangTuaIndexRoute: AuthRegisterOrangTuaIndexRoute,
  IntegrationsAzureKeyVaultOauth2CallbackIndexRoute:
    IntegrationsAzureKeyVaultOauth2CallbackIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_app",
        "/auth/login/",
        "/auth/register/",
        "/auth/verification/",
        "/auth/register/mahasiswa/",
        "/auth/register/orang-tua/",
        "/integrations/azure-key-vault/oauth2/callback/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/profile/",
        "/_app/protected-example/",
        "/_app/daftar/mahasiswa-saya/",
        "/_app/daftar/mahasiswa/"
      ]
    },
    "/_app/profile/": {
      "filePath": "_app/profile/index.tsx",
      "parent": "/_app"
    },
    "/_app/protected-example/": {
      "filePath": "_app/protected-example/index.tsx",
      "parent": "/_app"
    },
    "/auth/login/": {
      "filePath": "auth/login/index.tsx"
    },
    "/auth/register/": {
      "filePath": "auth/register/index.tsx"
    },
    "/auth/verification/": {
      "filePath": "auth/verification/index.tsx"
    },
    "/_app/daftar/mahasiswa-saya/": {
      "filePath": "_app/daftar/mahasiswa-saya/index.tsx",
      "parent": "/_app"
    },
    "/_app/daftar/mahasiswa/": {
      "filePath": "_app/daftar/mahasiswa/index.tsx",
      "parent": "/_app"
    },
    "/auth/register/mahasiswa/": {
      "filePath": "auth/register/mahasiswa/index.tsx"
    },
    "/auth/register/orang-tua/": {
      "filePath": "auth/register/orang-tua/index.tsx"
    },
    "/integrations/azure-key-vault/oauth2/callback/": {
      "filePath": "integrations/azure-key-vault/oauth2/callback/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
